---
#-------------------------------
# General Site Settings

title: plazarotello
logo:
author: Patricia Lázaro Tello
description: plazaro's portfolio
email: patricialazarotello@gmail.com
phone: +34 606 26 14 20
address: Zaragoza, Spain
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Blog, link: "/blog" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

# disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Patricia, <br> writer in the making, <br>comic enthusiast and <br>videogame developer

social:
  - { icon: "ti-instagram", link: "https://www.instagram.com/plazaro.dev/" }
  - { icon: "ti-twitter", link: "https://x.com/PLazaroTello" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: My two passions since I was little have been videogames and art. Being able to program a videogame, and doing it with ease in the last few years - using Unreal Engine 4, Unity and Godot 3 and 4 - is a dream made true. Learning to draw and not suck at it; that would be another dream come true. I have a lot of stories in my mind, just waiting for a pen to touch a paper, a key to be stroked, a comic to be thought or a videogame to be designed.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
# work-process:
#   - title: "Research and Plan"
#     icon: "assets/images/icons/plan.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Design and Develop"
#     icon: "assets/images/icons/design.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title: "Deliver"
#     icon: "assets/images/icons/print.png"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Data Analysis, color: "#ffbcaa", value: "75%" }
  - { name: Programming, color: "#ffbcaa", value: "85%" }
  - { name: Writing, color: "#bdecf6", value: "80%" }
  - { name: Comic making, color: "#9473e6", value: "30%" }

  - { name: Game design, color: "#fdb157", value: "40%" }
  - { name: Game programmer, color: "#fdb157", value: "70%" }
  - { name: Narrative designer, color: "#fdb157", value: "80%" }
  - { name: Social Media manager, color: "#fdb157", value: "35%" }
  
  - { name: Godot 3 & 4, color: "#df4090", value: "60%" }
  - { name: UE4, color: "#df4090", value: "40%" }
  - { name: Unity, color: "#df4090", value: "20%" }
  - { name: GameMaker, color: "#df4090", value: "28%" }

#-------------------------------
# Experience Section

experience-title: Experience
experience:
  - {
      name: Junior Programmer,
      icon: "icon-1.png",
      date: "Nov 2016 - Mar 2017",
      organization: "Hiberus Tecnologías de la Información",
    }
  - {
      name: Backend Engineer,
      icon: "icon-2.png",
      date: "Dec 2018 - May 2019",
      organization: "Datumize S.L.",
    }
  - {
      name: Videogame maker (programmer, narrative designer),
      icon: "icon-3.png",
      date: "Jun 2018 - Present",
      organization: "Kalpa Games & Otter Games",
    }
  - {
      name: Data Analyst,
      icon: "icon-3.png",
      date: "Jul 2022 - Present",
      organization: "Telefónica de España S.A.",
    }

#-------------------------------
# Education Section

education-title: Education
education:

  - {
      name: Data Science master,
      date: "2021-2023",
      honours: "Graduated with honours (9.67/10)",
      organization: "Universitat Oberta de Catalunya (UOC)",
    }
  - {
      name: Videogame Programming master,
      date: "2017-2018",
      organization: "Universidad Complutense de Madrid (UCM)",
    }
  - {
      name: Computer Science grade,
      date: "2012-2016",
      honours: "Average grade: 8.07/10",
      organization: "Universidad de Zaragoza (UNIZAR)",
    }
  - {
      name: Bachelor's degree,
      date: "2010-2012",
      honours: "Graduated with honours",
      organization: "Sagrada Familia",
    }

#-------------------------------
# Services Section

# services-title: Services
# services:
#   - {
#       name: UI Design,
#       icon: ti-palette,
#       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#       active: ,# Add true to select section
#     }
#   - {
#       name: UX Design,
#       icon: ti-vector,
#       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#       active: true, # Add true to select section
#     }
#   - {
#       name: Interaction Design,
#       icon: ti-panel,
#       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#       active: ,# Add true to select section
#     }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/simbiosis.jpg"
    url: "_portfolio_items/Simbiosis"
    internal: true

  - image: "assets/images/portfolio/imagination.jpg"
    url: "_portfolio_items/Imaginacion"
    internal: true

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    internal: false

  - image: "assets/images/portfolio/item-4.png"
    url: "#"
    internal: false

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    internal: false

# Portfolio Page
portfolio-label:
  - { title: "PROGRAMMING", type: "programming" }
  - { title: "DATA ANALYSIS", type: "analysis" }
  - { title: "WRITING", type: "writing" }
  - { title: "V-GAME MAKER", type: "videogame" }
  - { title: "COMIC", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/simbiosis.jpg"
    url: "_portfolio_items/Simbiosis"
    internal: true
    portfolio-type:
      - type: "writing"

  - image: "assets/images/portfolio/imagination.jpg"
    url: "#"
    internal: false
    portfolio-type:
      - type: "writing"

  - image: "assets/images/portfolio/mask.jpg"
    url: "#"
    internal: false
    portfolio-type:
      - type: "writing"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    internal: false
    portfolio-type:
      - type: "design"
      - type: "branding"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Contact Section

contact-title: Contact information
contact-email: patricialazarotello@gmail.com
